### ISSUE TITLE
MQTT connection (seeding db)

### ISSUE THREAD

**Issue by considine** [factn/coronadonor-api#4]
Is it necessary to do anything MQTT related to get the backend running locally?

After setting up a db (and configuring env) I'm hitting a glitch on the db:seed step in mqtt_me

```bash
{:remote_host=>"mosquitto", :remote_port=>1883, :username=>"mosquitto", :password=>""}
SocketError: getaddrinfo: nodename nor servname provided, or not known
```

**Comment by skrobul** [comment]
@considine looks like DNS cannot resolve `mosquitto` host.
If you are running this in dockerized environment, make sure that `mosquitto` service is started.
If it is, exec to api container and troubleshoot why it cannot be resolved.

I have just tried [setting up new dockerized environment](https://github.com/factn/coronadonor-api#run-via-dockerdocker-compose) instructions and they work correctly. 

MQTT [is initialized](https://github.com/factn/coronadonor-api/blob/9feb3c8f32669c6a5a18ab5075e2f8fcf7e169e6/app/models/application_record.rb#L8) here, so it will be automatically loaded during `db:seed`.

If you are not running the dockerized version, you may want to set the `CLOUDMQTT_URL` to something else.

**Comment by considine** [comment]
Thanks @skrobul !
I was using the non dockerized build and didn't see instructions for setting up mosquito.
Docker works
